[colors.primary]
background = "#0B0C16"
foreground = "#ddf7ff"

[colors.cursor]
text = "#0B0C16"
cursor = "#ddf7ff"

[colors.vi_mode_cursor]
text = "#0B0C16"
cursor = "#ddf7ff"

[colors.search.matches]
foreground = "#0B0C16"
background = "#ddf7ff"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a6e95"
background = "#ddf7ff"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0B0C16"
red = "#31f759"
green = "#4fe88f"
yellow = "#50f7d4"
blue = "#829dd4"
magenta = "#86a7df"
cyan = "#7cf8f7"
white = "#85E1FB"

[colors.bright]
black = "#6a6e95"
red = "#85ff9d"
green = "#9cf7c2"
yellow = "#a4ffec"
blue = "#c4d2ed"
magenta = "#cddbf4"
cyan = "#d1fffe"
white = "#ddf7ff"

[colors.dim]
black = "#ddf7ff"
red = "#85ff9d"
green = "#9cf7c2"
yellow = "#a4ffec"
blue = "#c4d2ed"
magenta = "#cddbf4"
cyan = "#d1fffe"
white = "#6a6e95"
