[colors.primary]
foreground = "#cccac2"
background = "#1f2430"

[colors.cursor]
text = "#1f2430"
cursor = "#cccac2"

[colors.selection]
text = "#cccac2"
background = "#274364"

[colors.normal]
black = "#171b24"
red = "#ed8274"
green = "#87d96c"
yellow = "#facc6e"
blue = "#6dcbfa"
magenta = "#dabafa"
cyan = "#90e1c6"
white = "#c7c7c7"

[colors.bright]
black = "#686868"
red = "#f28779"
green = "#d5ff80"
yellow = "#ffd173"
blue = "#73d0ff"
magenta = "#dfbfff"
cyan = "#95e6cb"
white = "#ffffff"
